{% set name = "leiningen" %}
{% set version = "2.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/technomancy/leiningen/archive/refs/tags/{{ version }}.tar.gz
    sha256: 5f4ae6ef2a9665176138730f00ce008b17de96af99a2ce5e4c3f017b2d4d5659
    folder: leiningen-src
  - url: https://github.com/technomancy/leiningen/releases/download/{{ version }}/leiningen-{{ version }}-standalone.jar
    sha256: d27299bad34075ac2864d0bd0559f835c6e2c476c0b0a283bcbdb574fdadbb34
    folder: leiningen-jar

build:
  number: 0

requirements:
  build:
    - openjdk
    - maven
  run:
    - openjdk

test:
  source_files:
    - leiningen-src
  commands:
    - test -f ${PREFIX}/bin/lein  # [unix]
    - test -f ${PREFIX}/lib/leiningen/libexec/leiningen-${PKG_VERSION}-standalone.jar  # [unix]

    - if not exist %PREFIX%\Scripts\lein.bat exit /b 1  # [win]

    - cd leiningen-src && lein test leiningen.test.test  # [unix]
    - lein version

about:
  home: https://codeberg.org/leiningen/leiningen
  summary: 'Leiningen is for automating Clojure projects without setting your hair on fire.'
  description: |
    "Leiningen!" he shouted. "You're insane! They're not creatures you can
    fight—they're an elemental—an 'act of God!' Ten miles long, two miles
    wide—ants, nothing but ants! And every single one of them a fiend from hell..."
      from Leiningen Versus the Ants by Carl Stephenson
  license: EPL-1.0
  license_file:
    - COPYING
    - THIRD-PARTY.txt

extra:
  recipe-maintainers:
    - MementoRC
