{% set name = "leiningen" %}
{% set version = "2.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/technomancy/leiningen/archive/refs/tags/{{ version }}.tar.gz
  sha256: cae3bbb9e5f07ff518b9b35ecfe070066ea074f2cb15ffb0a73ad7fe2a2683cf
  folder: leiningen-src

build:
  noarch: generic
  number: 0

requirements:
  build:
    - openjdk
    - openssh
    - maven
  run:
    - openjdk

test:
  source_files:
    - leiningen-src
  commands:
    - test -f ${PREFIX}/bin/lein
    - test -f ${PREFIX}/lib/leiningen/libexec/leiningen-${PKG_VERSION}-standalone.jar

    - cd leiningen-src
    - lein test leiningen.test.test | grep failures
    - lein version

about:
  home: https://codeberg.org/leiningen/leiningen
  summary: 'Leiningen is for automating Clojure projects without setting your hair on fire.'
  description: |
    "Leiningen!" he shouted. "You're insane! They're not creatures you can
    fight—they're an elemental—an 'act of God!' Ten miles long, two miles
    wide—ants, nothing but ants! And every single one of them a fiend from hell..."
      from Leiningen Versus the Ants by Carl Stephenson
  license: EPL-1.0
  license_file:
    - COPYING
    - THIRD-PARTY.txt

extra:
  recipe-maintainers:
    - MementoRC
